name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout
        uses: actions/checkout@v5
  
      - name: Generate
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.MY_3D_STATS }}
          USERNAME: ${{ github.repository_owner }}
  
      - name: Commit & Push
        run: |
          git config user.name "rmflsdl4"
          git config user.email "rmflsdl4@gmail.com"
          git add -A .
          if ! git diff --staged --quiet; then
              git commit -m "Update 3D Contribution"
              git push
          fi
